version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8082:80"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./node_modules:/app/node_modules
      - ./default.conf:/app/default.conf
    environment:
      NODE_ENV: development
